export default {
  GITHUB_CLIENT_ID: process.env.REACT_APP_GITHUB_CLIENT_ID,
  API_URL: process.env.REACT_APP_API_URL,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
  ROLLBAR_ACCESS_TOKEN: process.env.REACT_APP_ROLLBAR_ACCESS_TOKEN,
};
